[2024-10-06T14:54:52.343+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T14:54:52.355+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: send_to_snowflake.create_raw_dataframe manual__2024-10-06T14:54:50.880381+00:00 [queued]>
[2024-10-06T14:54:52.361+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: send_to_snowflake.create_raw_dataframe manual__2024-10-06T14:54:50.880381+00:00 [queued]>
[2024-10-06T14:54:52.361+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2024-10-06T14:54:52.374+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): create_raw_dataframe> on 2024-10-06 14:54:50.880381+00:00
[2024-10-06T14:54:52.382+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1610) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T14:54:52.383+0000] {standard_task_runner.py:72} INFO - Started process 1612 to run task
[2024-10-06T14:54:52.384+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'send_to_snowflake', 'create_raw_dataframe', 'manual__2024-10-06T14:54:50.880381+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/test_send.py', '--cfg-path', '/tmp/tmpq8g9yqes']
[2024-10-06T14:54:52.386+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask create_raw_dataframe
[2024-10-06T14:54:52.429+0000] {task_command.py:467} INFO - Running <TaskInstance: send_to_snowflake.create_raw_dataframe manual__2024-10-06T14:54:50.880381+00:00 [running]> on host 3749aa3641b5
[2024-10-06T14:54:52.629+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='send_to_snowflake' AIRFLOW_CTX_TASK_ID='create_raw_dataframe' AIRFLOW_CTX_EXECUTION_DATE='2024-10-06T14:54:50.880381+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-06T14:54:50.880381+00:00'
[2024-10-06T14:54:52.631+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T14:54:52.666+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-06T14:54:52.676+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T14:54:52.677+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=send_to_snowflake, task_id=create_raw_dataframe, run_id=manual__2024-10-06T14:54:50.880381+00:00, execution_date=20241006T145450, start_date=20241006T145452, end_date=20241006T145452
[2024-10-06T14:54:52.720+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T14:54:52.736+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-06T14:54:52.743+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
