[2024-10-06T14:53:09.817+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T14:53:09.829+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: send_to_snowflake.create_raw_dataframe manual__2024-10-06T14:53:07.816177+00:00 [queued]>
[2024-10-06T14:53:09.834+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: send_to_snowflake.create_raw_dataframe manual__2024-10-06T14:53:07.816177+00:00 [queued]>
[2024-10-06T14:53:09.834+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2024-10-06T14:53:09.849+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): create_raw_dataframe> on 2024-10-06 14:53:07.816177+00:00
[2024-10-06T14:53:09.858+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1581) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T14:53:09.859+0000] {standard_task_runner.py:72} INFO - Started process 1583 to run task
[2024-10-06T14:53:09.860+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'send_to_snowflake', 'create_raw_dataframe', 'manual__2024-10-06T14:53:07.816177+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/test_send.py', '--cfg-path', '/tmp/tmpn0_ad7kq']
[2024-10-06T14:53:09.862+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask create_raw_dataframe
[2024-10-06T14:53:09.914+0000] {task_command.py:467} INFO - Running <TaskInstance: send_to_snowflake.create_raw_dataframe manual__2024-10-06T14:53:07.816177+00:00 [running]> on host 3749aa3641b5
[2024-10-06T14:53:09.995+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='send_to_snowflake' AIRFLOW_CTX_TASK_ID='create_raw_dataframe' AIRFLOW_CTX_EXECUTION_DATE='2024-10-06T14:53:07.816177+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-06T14:53:07.816177+00:00'
[2024-10-06T14:53:09.996+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T14:53:10.026+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-06T14:53:10.034+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T14:53:10.034+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=send_to_snowflake, task_id=create_raw_dataframe, run_id=manual__2024-10-06T14:53:07.816177+00:00, execution_date=20241006T145307, start_date=20241006T145309, end_date=20241006T145310
[2024-10-06T14:53:10.073+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T14:53:10.089+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-06T14:53:10.097+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
