[2024-10-06T14:58:12.912+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T14:58:12.925+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: send_to_snowflake.upload_raw_to_snowflake manual__2024-10-06T14:53:07.816177+00:00 [queued]>
[2024-10-06T14:58:12.931+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: send_to_snowflake.upload_raw_to_snowflake manual__2024-10-06T14:53:07.816177+00:00 [queued]>
[2024-10-06T14:58:12.931+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 4
[2024-10-06T14:58:12.945+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): upload_raw_to_snowflake> on 2024-10-06 14:53:07.816177+00:00
[2024-10-06T14:58:12.958+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1668) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-06T14:58:12.960+0000] {standard_task_runner.py:72} INFO - Started process 1670 to run task
[2024-10-06T14:58:12.957+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'send_to_snowflake', 'upload_raw_to_snowflake', 'manual__2024-10-06T14:53:07.816177+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/test_send.py', '--cfg-path', '/tmp/tmprtdjpm1m']
[2024-10-06T14:58:12.961+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask upload_raw_to_snowflake
[2024-10-06T14:58:13.009+0000] {task_command.py:467} INFO - Running <TaskInstance: send_to_snowflake.upload_raw_to_snowflake manual__2024-10-06T14:53:07.816177+00:00 [running]> on host 3749aa3641b5
[2024-10-06T14:58:13.117+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='send_to_snowflake' AIRFLOW_CTX_TASK_ID='upload_raw_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2024-10-06T14:53:07.816177+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-06T14:53:07.816177+00:00'
[2024-10-06T14:58:13.118+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T14:58:13.151+0000] {warnings.py:112} WARNING - /opt/***/dags/test_send.py:64: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(df_json)

[2024-10-06T14:58:13.170+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2024-10-06T14:58:13.171+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.2, Python Version: 3.12.6, Platform: Linux-6.5.0-1025-azure-x86_64-with-glibc2.36
[2024-10-06T14:58:13.172+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2024-10-06T14:58:13.173+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-10-06T14:58:13.587+0000] {warnings.py:112} WARNING - /opt/***/dags/test_send.py:82: UserWarning: Pandas Dataframe has non-standard index of type <class 'pandas.core.indexes.base.Index'> which will not be written. Consider changing the index to pd.RangeIndex(start=0,...,step=1) or call reset_index() to keep index as column(s)
  success, nchunks, nrows, _ = write_pandas(

[2024-10-06T14:58:13.871+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2024-10-06T14:58:14.256+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2024-10-06T14:58:15.078+0000] {cursor.py:1156} INFO - Number of results in first chunk: 7
[2024-10-06T14:58:15.140+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2024-10-06T14:58:16.670+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2024-10-06T14:58:16.670+0000] {logging_mixin.py:190} INFO - Successfully uploaded 5 rows in 1 chunks to RAW_EMPLOYEE_DATA in Snowflake.
[2024-10-06T14:58:16.671+0000] {connection.py:788} INFO - closed
[2024-10-06T14:58:16.687+0000] {connection.py:794} INFO - No async queries seem to be running, deleting session
[2024-10-06T14:58:16.722+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-06T14:58:16.731+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T14:58:16.731+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=send_to_snowflake, task_id=upload_raw_to_snowflake, run_id=manual__2024-10-06T14:53:07.816177+00:00, execution_date=20241006T145307, start_date=20241006T145812, end_date=20241006T145816
[2024-10-06T14:58:16.797+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T14:58:16.810+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-06T14:58:16.851+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
